workflows:
  build-apk:
    name: Build and Push APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - your_group_name # Укажите нужную группу переменных окружения, если есть
      vars:
        JAVA_HOME: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: ./gradlew dependencies
      - name: Build APK
        script: ./gradlew assembleRelease
      - name: Configure git
        script: |
          git config --global user.email "kasteroww@mail.ru"
          git config --global user.name "Kasteroww"
      - name: Commit APK
        script: |
          mkdir -p apk
          cp app/build/outputs/apk/release/app-release.apk ./apk/app-release.apk
          git add ./apk/app-release.apk
          git commit -m "Add latest APK build"
          git push origin HEAD:main
