workflows:
  build-apk:
    name: Build and Push APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Configure git
        script: |
          git config --global user.email "kasteroww@mail.ru"
          git config --global user.name "Kasteroww"
      - name: Commit APK
        script: |
          mkdir -p apk
          cp build/app/outputs/flutter-apk/app-release.apk ./apk/app-release.apk
          git add ./apk/app-release.apk
          git commit -m "Add latest APK build"
          git push origin HEAD:main
